export  const departamentos = [
  "Amazonas",
  "Antioquia",
  "Arauca", 
  "Atlántico",
  "Bolívar", 
  "Boyacá", 
  "Caldas", 
  "Caquetá", 
  "Casanare", 
  "Cauca", 
  "Cesar", 
  "Chocó", 
  "Córdoba", 
  "Cundinamarca", 
  "Guainía", 
  "Guaviare", 
  "Huila", 
  "Guajira", 
  "Magdalena", 
  "Meta", 
  "Nariño", 
  "Norte de Santander", 
  "Putumayo", 
  "Quindío", 
  "Risaralda", 
  "San Andrés y Providencia", 
  "Santander", 
  "Sucre", 
  "Tolima", 
  "Valle del Cauca", 
  "Vaupés", 
  "Vichada"
];

export const ciudades: { [key: string]: string[] } = {
  Amazonas: ["Leticia", "Puerto Nariño", "La Pedrera"],
  Antioquia: ["Medellín", "Envigado", "Bello"],
  Arauca: ["Arauca", "Saravena", "Arauquita"],
  Atlántico: ["Barranquilla", "Soledad", "Malambo"],
  Bolívar: ["Cartagena", "Magangué", "Turbaco"],
  Boyacá: ["Tunja", "Duitama", "Sogamoso"],
  Caldas: ["Manizales", "Chinchiná", "Villamaría"],
  Caquetá: ["Florencia", "Milán", "Solano"],
  Casanare: ["Yopal", "Aguazul", "Villanueva"],
  Cauca: ["Popayán", "Santander de Quilichao", "Puerto Tejada"],
  Cesar: ["Valledupar", "Aguachica", "Bosconia"],
  Chocó: ["Quibdó", "Istmina", "Acandí"],
  Córdoba: ["Montería", "Cereté", "Lorica"],
  Cundinamarca: ["Bogotá", "Soacha", "Zipaquirá"],
  Guainía: ["Inírida", "Barranco Minas", "La Guadalupe"],
  Guaviare: ["San José del Guaviare", "Calamar", "Miraflores"],
  Huila: ["Neiva", "Pitalito", "Garzón"],
  Guajira: ["Riohacha", "Maicao", "Uribia"],
  Magdalena: ["Santa Marta", "Ciénaga", "El Banco"],
  Meta: ["Villavicencio", "Acacías", "Granada"],
  Nariño: ["Pasto", "Tumaco", "Ipiales"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona"],
  Putumayo: ["Mocoa", "Puerto Asís", "Sibundoy"],
  Quindío: ["Armenia", "Montenegro", "Quimbaya"],
  Risaralda: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"],
  "San Andrés y Providencia": ["San Andrés", "Providencia", "La Loma"],
  Santander: ["Bucaramanga", "Floridablanca", "Barrancabermeja"],
  Sucre: ["Sincelejo", "Corozal", "Sampués"],
  Tolima: ["Ibagué", "Espinal", "Melgar"],
  "Valle del Cauca": ["Cali", "Palmira", "Buenaventura"],
  Vaupés: ["Mitú", "Caruru", "Papunaua"],
  Vichada: ["Puerto Carreño", "La Primavera", "Cumaribo"]
};